export const WEATHER_DESCRIPTIONS: Record<number, string> = {
    0: 'Clear Sky',
    1: 'Mainly Clear',
    2: 'Partly Cloudy',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing Rime Fog',
    51: 'Light Drizzle',
    53: 'Moderate Drizzle',
    55: 'Dense Drizzle',
    56: 'Light Freezing Drizzle',
    57: 'Dense Freezing Drizzle',
    61: 'Slight Rain',
    63: 'Moderate Rain',
    65: 'Heavy Rain',
    66: 'Light Freezing Rain',
    67: 'Heavy Freezing Rain',
    71: 'Slight Snow Fall',
    73: 'Moderate Snow Fall',
    75: 'Heavy Snow Fall',
    77: 'Snow grains',
    80: 'Light Rain Shower',
    81: 'Moderate Rain Shower',
    82: 'Violent Rain Shower',
    85: 'Slight Snow Shower',
    86: 'Heavy Snow Shower',
    95: 'Thunderstorm',
    96: 'Thunderstorm with Slight Hail',
    99: 'Thunderstorm with Heavy Hail',
}

export const DEFAULT_DATA = {
    day_name: 'Today',
    city_name: '',
    latitude: 0,
    longitude: 0,
    current: {
        day_name: 'Today',
        temperature: 0,
        temperature_max: 0,
        temperature_min: 0,
        weathercode: 0,
        weathercode_description: '',
        imageUrl: '',
        aqi: 50,
        aqi_description: '',
        aqi_color: '',
    },
    hourly: {},
    daily: {},
};

export const WEATHER_ICONS: Record<number, string> = {
    0: 'clear.png',
    1: 'clear.png',
    2: 'cloudy_sunny.png',
    3: 'overcast.png',
    45: 'fog.png',
    48: 'fog.png',
    51: 'cloudy_sunny_rain.png',
    53: 'cloudy_sunny_rain.png',
    55: 'cloudy_sunny_rain.png',
    56: 'cloudy_rainy.png',
    57: 'cloudy_rainy.png',
    61: 'cloudy_rainy.png',
    63: 'cloudy_rainy.png',
    65: 'cloudy_rainy.png',
    66: 'cloudy_rainy.png',
    67: 'cloudy_rainy.png',
    71: 'snowy.png',
    73: 'snowy.png',
    75: 'snowy.png',
    77: 'snowy.png',
    80: 'cloudy_rainy.png',
    81: 'cloudy_rainy.png',
    82: 'cloudy_rainy.png',
    85: 'cloudy_rainy.png',
    86: 'cloudy_rainy.png',
    95: 'thunderstorm.png',
    96: 'thunderstorm.png',
    99: 'thunderstorm.png',
}

export const USA_STATE_CAPITAL_NAMES = [
    'Montgomery',
    'Juneau',
    'Phoenix',
    'Little Rock',
    'Sacramento',
    'Denver',
    'Hartford',
    'Dover',
    'Tallahassee',
    'Atlanta',
    'Honolulu',
    'Boise',
    'Springfield',
    'Indianapolis',
    'Des Moines',
    'Topeka',
    'Frankfort',
    'Baton Rouge',
    'Augusta',
    'Annapolis',
    'Boston',
    'Lansing',
    'Saint Paul',
    'Jackson',
    'Jefferson City',
    'Helena',
    'Lincoln',
    'Carson City',
    'Concord',
    'Trenton',
    'Santa Fe',
    'Albany',
    'Raleigh',
    'Bismarck',
    'Columbus',
    'Oklahoma City',
    'Salem',
    'Harrisburg',
    'Providence',
    'Columbia',
    'Pierre',
    'Nashville',
    'Austin',
    'Salt Lake City',
    'Montpelier',
    'Richmond',
    'Olympia',
    'Charleston',
    'Madison',
    'Cheyenne',
];